doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: pdo_sqlite
        path: '%kernel.project_dir%/var/data.db'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App 